<?php

$modversion['name'] = _OP_MYSQL_NAME;
$modversion['version'] = 2.14;
$modversion['description'] = _OP_MYSQL_DESC;
$modversion['credits'] = 'Peter Nagl<br>http://www.nagl.ch';
$modversion['author'] = 'webmaster@nagl.ch';
$modversion['help'] = '';
$modversion['license'] = 'GPL see LICENSE';
$modversion['official'] = 0;
$modversion['image'] = 'images/slogo.png';
$modversion['dirname'] = 'optimize';

//Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = 'admin/index.php';
$modversion['adminmenu'] = 'admin/menu.php';

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = 'sql/mysql.sql';

// Tables created by sql file (without prefix!)
$modversion['tables'][0] = 'optimize_gain';

// Menu
$modversion['hasMain'] = 0;
